# Generated by Django 4.1.6 on 2023-02-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_last_attempt', models.CharField(default=None, max_length=100, verbose_name='Дата последней попытки')),
                ('time_of_last_attempt', models.CharField(default=None, max_length=150, verbose_name='Время последней попытки')),
                ('attempt_status', models.CharField(default=None, max_length=150, verbose_name='Статус попытки')),
                ('mail_server_response', models.TextField(default=None, verbose_name='Статус попытки')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронка')),
                ('mame', models.CharField(default=None, max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(default=None, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_time', models.TimeField(blank=True, verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[('once a day', 'раз в день'), ('once a week', 'раз в неделю'), ('once a month', 'раз в месяц')], default='once a day', max_length=20)),
                ('mailing_status', models.CharField(choices=[('completed,', 'завершена'), ('created', 'создана'), ('launched,', 'запущена')], default='created', max_length=20)),
                ('client', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='spammy.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MessageToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_subject', models.CharField(blank=True, default=None, max_length=100, verbose_name='Тема письма')),
                ('body_of_the_letter', models.CharField(blank=True, default=None, max_length=150, verbose_name='Тело письма')),
                ('newsletter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='spammy.newsletter', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщение для рассылок',
            },
        ),
    ]
