# Generated by Django 4.1.6 on 2023-02-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempttosend',
            name='mail_server_response',
            field=models.TextField(default=None, verbose_name='Ответ сервера'),
        ),
        migrations.AlterField(
            model_name='messagetosend',
            name='body_of_the_letter',
            field=models.TextField(blank=True, default=None, max_length=1000, verbose_name='Тело письма'),
        ),
    ]
