# Generated by Django 4.1.6 on 2023-02-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spammy', '0002_alter_attempttosend_mail_server_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='client',
        ),
        migrations.CreateModel(
            name='NewsletterSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default=None, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spammy.client')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spammy.newsletter')),
            ],
            options={
                'verbose_name': 'Клиент-Рассылка (кому-что)',
                'verbose_name_plural': 'Клиент-Рассылка (кому-что)',
            },
        ),
        migrations.AddField(
            model_name='newsletter',
            name='addressee',
            field=models.ManyToManyField(through='spammy.NewsletterSystem', to='spammy.client', verbose_name='Адресат'),
        ),
    ]
