# Generated by Django 4.1.6 on 2023-02-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammy', '0006_alter_client_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersystem',
            name='comment',
            field=models.TextField(default='Type here...', verbose_name='Комментарий'),
        ),
    ]
