# Generated by Django 4.1.6 on 2023-02-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammy', '0008_remove_newsletter_addressee_newsletter_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='posting_date',
            field=models.DateField(default='2023-12-29', verbose_name='Когда'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='posting_time',
            field=models.TimeField(default='00:01', verbose_name='Во сколько'),
        ),
    ]
